### ISSUE TITLE
Variable "google_logging_enabled" is declared but not used

### ISSUE THREAD

**Issue by d-costa** [runatlantis/terraform-gce-atlantis#129]
First of all, thank you for developing this module, it is extremely useful.

I noticed the variable `google_logging_enabled` is not used, and the monitoring variable is used to set the logging metadata on the compute instance. Is this behavior intended?

https://github.com/bschaatsbergen/terraform-gce-atlantis/blob/263a41ab20befe5c9a8f7b584ae6e2a6e69c4167/main.tf#L132-L133

PS: I don't mind raising a PR if this is indeed not intended

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue, good spot!
