### ISSUE TITLE
Support persistent_disk_type input in atlantis module

### ISSUE THREAD

**Issue by knjoroge** [runatlantis/terraform-gce-atlantis#158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.

---

Hello,

It would be nice to have `persistent_disk_type` as an input in the atlantis module as not everyone has a use case where they need a SSD provisioned.

https://github.com/runatlantis/terraform-gce-atlantis?tab=readme-ov-file#inputs

https://cloud.google.com/compute/docs/disks#introduction

**Comment by bschaatsbergen** [comment]
Great feature request @knjoroge - thank you for taking the time to raise this issue.

**Comment by knjoroge** [comment]
@d-costa @bschaatsbergen thank you! Do you know when you're planning to have this released?
